app <- ShinyDriver$new("../../", loadTimeout = 1e+04)
app$snapshotInit("FilterEBV-UserData")

app$uploadFile(`step1-desc_ebv-file` = "../../data/description_bv.xlsx") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$uploadFile(`step1-dat_ebv-file` = "../../data/bv.csv") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$uploadFile(`step1-desc_ev-file` = "../../data/description_ev.csv") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$uploadFile(`step1-dat_ev-file` = "../../data/ev.csv") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$snapshot()
app$setInputs(upload = "tab.step2")
app$snapshot()
app$setInputs(`ebv_filter-view_vars` = "ID")
app$setInputs(`ebv_filter-view_vars` = "sex")
app$setInputs(`ebv_filter-view_vars` = "ID")
app$setInputs(`ebv_filter-view_vars` = c("ID", "sex"))
app$setInputs(`ebv_filter-view_vars` = c("ID", "sex", "GLEAFSPOT"))
app$setInputs(`ebv_filter-view_vars` = c("ID", "sex", "GLEAFSPOT", "ANTHRAC"))
app$setInputs(`ebv_filter-view_store` = "click")
app$snapshot()
app$setInputs(upload = "tab.ebv.sumstat")
app$snapshot()
app$setInputs(`sumstat_ebv-vars` = "sex{character}")
app$setInputs(`sumstat_ebv-vars` = c("sex{character}", "GLEAFSPOT{double}"))
app$snapshot(list(output = "sumstat_ebv-ui_vars"))
app$setInputs(`sumstat_ebv-create_table` = "click", timeout_ = 10000)
app$snapshot()
app$setInputs(upload = "tab.step3")
app$setInputs(`ev_filter-view_vars` = "Index")
app$setInputs(`ev_filter-view_vars` = c("Index", "YIELD"))
app$setInputs(`ev_filter-view_vars` = c("Index", "YIELD", "GREENSNAP"))
app$setInputs(`ev_filter-view_vars` = c("Index", "YIELD", "GREENSNAP", "EMERG"))
app$setInputs(`ev_filter-view_store` = "click")
app$setInputs(upload = "tab.ev.sumstat")
app$setInputs(`sumstat_ev-vars` = "EMERG{double}")
app$setInputs(`sumstat_ev-vars` = c("YIELD{double}", "EMERG{double}"))
app$snapshot(list(output = "sumstat_ev-ui_vars"))
app$setInputs(`sumstat_ev-create_table` = "click",  timeout_ = 10000)
app$snapshot()
