app <- ShinyDriver$new("../../", loadTimeout = 1e+04)
app$snapshotInit("FilterEBV-NoData")

app$setInputs(upload = "tab.step2")
app$snapshot()
app$setInputs(upload = "tab.step3")
app$snapshot()
app$setInputs(upload = "tab.ebv.sumstat")
app$snapshot()
app$setInputs(upload = "tab.ev.sumstat")
app$snapshot()
