app <- ShinyDriver$new("../../", loadTimeout = 1e+05)
app$snapshotInit("test-help-preprocess")

app$setInputs(`step1-help_btn` = "click")
app$snapshot()
app$setInputs(`step1-help_btn` = "click")
app$snapshot()
app$setInputs(demo = "click")
app$setInputs(upload = "tab.step2")
app$snapshot()
app$setInputs(help_btn_ebv_filter = "click")
app$snapshot()
app$setInputs(help_btn_ebv_filter = "click")
app$setInputs(`ebv_filter-view_vars` = "ID")
app$setInputs(`ebv_filter-view_vars` = c("ID", "FUSARIUM"))
app$setInputs(`ebv_filter-view_vars` = c("ID", "FUSARIUM", "GIBBERELLA"))
app$setInputs(`ebv_filter-view_store` = "click")
app$setInputs(upload = "tab.ebv.sumstat")
app$setInputs(`sumstat_ebv-vars` = "GIBBERELLA{double}")
app$setInputs(`sumstat_ebv-help_btn` = "click")
app$snapshot()
app$setInputs(`sumstat_ebv-help_btn` = "click")
app$setInputs(`sumstat_ebv-create_table` = "click")
app$snapshot()
